language: java
jdk:
- oraclejdk8
script: gradle test uploadArchives closeAndReleaseRepository -Pversion="1.0.${TRAVIS_BUILD_NUMBER}"
  --refresh-dependencies
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_install:
- openssl aes-256-cbc -K $encrypted_c13ae4391b00_key -iv $encrypted_c13ae4391b00_iv
  -in secret-keys.gpg.enc -out secret-keys.gpg -d
- openssl aes-256-cbc -K $encrypted_c13ae4391b00_key -iv $encrypted_c13ae4391b00_iv
  -in gradle.properties.enc -out gradle.properties -d
