language: java

jdk:
  - oraclejdk11

install: true

if: tag IS present

script: make release

cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.gradle/wrapper"

before_install:
  - wget https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
  - unzip -qq gradle-5.6.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH

  - openssl aes-256-cbc -K $encrypted_c13ae4391b00_key -iv $encrypted_c13ae4391b00_iv
    -in travis-secrets.tar.enc -out travis-secrets.tar -d

  - tar xvf travis-secrets.tar
